baseurl: "http://gonorthwest.io/"
title: "Go Northwest 2018"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "UA-117356578-1"

params:
  # Conference info
  Name: "Go Northwest 2018"
  Description: "A Go conference in the Pacific Northwest"
  Date: "July 30"
  Price: "Only $100"
  Venue: "McCaw Hall - Seattle Center"
  Address: "321 Mercer Street"
  City:  "Seattle"
  State: "WA"
  Images: ["/img/cover.png"]
  GoogleMapsKey: "AIzaSyBzZaKwhrfgXeoNCOz9lnU9TTyDOejoFi4"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - location
    - about
    - community
    - schedule
    - speakers
    #- diversity
    - sponsors
    - organizers
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    sponsors: "Sponsors"
    community: "Community"
    speakers: "Speakers"
    organizers: "Organizers"
    contact: "Contact"
    diversity: "Diversity Scholarships"
    schedule: "Schedule"


  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://gonorthwest.ticketbud.com/gonortwest2018"

  # List of Sponsors
  Sponsors:
    - name: "Axon"
      logo: "/img/axon.png"
      url: "http://www.axon.com"
    - name: "Igneous Systems"
      logo: "/img/igneous.png"
      url: "http://www.igneoussystems.com"
    - name: "Splunk"
      logo: "/img/splunk.png"
      url: "http://www.splunk.com"

  # The conference organizers
  Organizers:
    - name: "Ryan Cox"
      photo: "/img/ryan.png"
      url: "https://twitter.com/ryancox"
      bio: "Conference Chair"
    - name: "Brittany Walentin"
      photo: "/img/brittany.png"
      url: "https://twitter.com/brittzsta"
    - name: "Jake Sanders"
      photo: "/img/jake.png"
      url: "https://twitter.com/dekkagaijin"
    - name: "Yves Junqueira"
      photo: "/img/yves.png"
      url: "https://twitter.com/cetico"
    - name: "Samuel Karp"
      photo: "/img/sam.png"
      url: "https://twitter.com/samuelkarp"
    - name: "Tiffany Jernigan"
      photo: "/img/tiffany.png"
      url: "https://twitter.com/tiffanyfayj"

  # List of speakers and the schedule times
  Schedule:
    - presentation:
        time: 9:00
        title: Kickoff
    - name: Tess Rinearson
      photo: "/img/tessrinearson.jpg"
      presentation:
        title: An Over-Engineering Disaster with Macaroons
        time: 9:05
      bio: "Tess Rinearson is a software engineer at Chain, where she
      works on Chain Core, an open source, enterprise-grade blockchain.
      Previously, Tess was a full-stack engineer at Medium, where she
      helped build the social graph service and other infrastructure.
      She studied computer science at the University of Pennsylvania
      and Carnegie Mellon University."
      company: "Chain"
      link:
        href: "https://twitter.com/_tessr"
        text: "@_tessr"
    - name: Sam Kreter
      photo: "/img/samkreter.jpg"
      presentation:
        title: Introduction to Modern Data Science with Go
        time: 9:35
      bio: "Sam Kreter is a software engineer at Microsoft
      working on Azure Container Instances built on Kubernetes.
      Previously, he worked as a research assistant at the Center
      for Geospatial Intelligence, based out of the University of
      Missouri, building real-time video tracking software. He is
      obsessed with Go and loves bringing it into any project possible."
      company: "Microsoft"
      link:
        href: "https://twitter.com/samkreter"
        text: "@samkreter"
    - name: Michael Sorens
      photo: "/img/msorens.jpg"
      presentation:
        title: "Unit Testing: Tips from the Trenches"
        time: 10:05
      bio: "Michael Sorens, a software engineer at Chef Software, is
      passionate about the craft of software design and development--and
      sharing that passion. He has over 100 published articles and wallcharts,
      4 open-source projects, over 22K reputation on StackOverflow, and has
      taught/presented both inside and outside the workplace. He has worked
      in over 2 dozen languages, so brings a unique background to understanding
      the Go ecosystem. His favorite project to date: designing and implementing
      the world's smallest word processor, where the medium was silicon, the
      printer 'head' was a laser, and the Declaration of Independence literally
      fit on the head of a pin."
      company: "Chef"
    - presentation:
        time: 10:15
        title: Break
    - name: Jeffrey Richter
      photo: "/img/jeffrey.jpeg"
      presentation:
        title: "Using Reflection to implement enumerated types"
        time: 10:30
      bio: "Jeffrey Richter is an Azure Software Architect and authored several
      best-selling Windows & .NET programming books as well as many MSDN magazine
      articles. He is also a co-founder of Wintellect, a software consulting and
      training company where he has authored many videos available on WintellectNOW."
      company: "Microsoft"
      link:
        href: "https://twitter.com/JeffRichter"
        text: "@JeffRichter"
    - name: David Crawshaw
      photo: "/img/crawshaw.jpg"
      presentation:
        title: SQLite and Go
        time: 11:00
      bio: "David Crawshaw is a software engineer. Until recently he worked
      at Google on the Go programming language. He is currently working on
      something new."
      link:
        href: "https://twitter.com/davidcrawshaw"
        text: "@davidcrawshaw"
    - name: Hsing-Hui Hsu
      photo: "/img/hsinghui.jpg"
      presentation:
        title: A Rubyist’s (poignant) guide to Go
        time: 11:30
      bio: "Hsing-Hui is a Gopher by day and Rubyist by night. She is an
      alum of the first cohort of Ada Developers Academy and currently works
      as an open source maintainer. She likes learning languages (both computer
      and human), cleaning up code, and petting all the good doggos."
      link:
        href: "https://twitter.com/SoManyHs"
        text: "@SoManyHs"
    - presentation:
        time: 12:00
        title: Lunch
    - name: Jose Niño
      photo: "/img/josenino.png"
      presentation:
        time: 1:30
        title: Go in the Envoy Ecosystem
      bio: "Jose is the lead for Dev Tooling and Configuration on the
      Networking team at Lyft. During the nearly two years he's been at Lyft,
      Jose has been instrumental in creating systems to scale configuration of
      Lyft's Envoy production environment for increasingly large deployments
      and engineering orgs. He has worked as an open source Envoy maintainer,
      and he has nurtured Envoy's growing community. More recently, Jose
      has moved on to scaling Lyft's network load tolerance systems. Jose
      has spoken about Envoy and other related topics at several venues,
      most recently at Kubecon EU 2018."
      company: "Lyft"
      link:
        href: "https://twitter.com/junr03"
        text: "@junr03"
    - name: Stephen McQuay
      photo: "/img/stephen.jpg"
      presentation:
        time: 1:40
        title: Go idioms discovered building a system package manager
      bio: "Stephen studied mechanical engineering where he fell in love
      with coaxing computers to help him solve problems. He has spent the
      past five years building distributed systems and infrastructure software.
      He enjoys making music, playing (and typically losing) the game of Go,
      and hiking with his children."
      link:
        href: "https://twitter.com/smcquay"
        text: "@smcquay"
    - name: Jaana Burcu Dogan
      photo: "/img/jbd.jpg"
      presentation:
        title: Tracing Go
        time: 2:10
      bio: "Jaana B. Dogan is working on OpenCensus, an instrumentation framework
      for distributed systems, at Google. Previously, she worked on Go and has a
      decade-long experience in building developer platforms and tools."
      company: "Google"
      link:
        href: "https://twitter.com/rakyll"
        text: "@rakyll"
    - presentation:
        time: 2:40
        title: Break
    - name: Hayley Denbraver
      photo: "/img/hdenbraver.jpg"
      presentation:
        time: 2:55
        title: "We Are 3000 Years Behind: Let's Talk About Engineering Ethics"
      bio: "Hayley Denbraver is a web developer in San Diego, California.
      She is a career switcher who used to work as a licensed civil engineer.
      Her civil engineering projects included working on a hotel near Disneyland
      (It is awesome!) and anchoring air conditioners to hospital roofs
      (They are awesome too!). As a civil engineer she had a stamp with her
      name on it, but as a web developer you can find her name by using git
      blame. Hayley is an avid contributor to her company's #cute-animals
      slack channel. The best part of her job includes helping to onboard new,
      internally trained devs. She is a member of a two developer household,
      which you should consider before accepting her dinner party invitation.
      Hayley's 2018 stretch goal is to acquire a golden retriever--name
      suggestions are welcome."
      link:
        href: "https://twitter.com/hayleydenb"
        text: "@hayleydenb"
    - name: Gavin Chun Jin
      photo: "/img/gavin.jpg"
      presentation:
        time: 3:25
        title: Implementing ping(8) in Go
      bio: "Gavin Chun Jin is a software developer turned devops engineer.
      He programs mostly in Python & Go. His interests are in cryptography,
      philosophy & trail running. Once, he beat Ben Gibbard (lead singer
      of Death Cab for Cutie) - in an ultra-marathon."
      link:
        href: "https://twitter.com/GavinGastown3"
        text: "@GavinGastown3"
    - name: Katrina Ellison Geltman
      photo: "/img/katrina.png"
      presentation:
        time: 3:35
        title: "Code Generation: Go's Secret Weapon"
      bio: "Katrina is a software engineer at cloud hosting provider DigitalOcean,
      where her team creates tools for building and interacting with virtual machines.
      In her spare time, she likes skiing and hiking."
      company: "Digital Ocean"
      link:
        href: "http://katrinaeg.com/"
        text: "katrina"
    - presentation:
        time: 3:50
        title: Break
    - name: Jayapriya Surendran
      photo: "/img/Jayapriya.jpg"
      presentation:
        time: 4:00
        title: Probabilistic Data Structures Using Go
      bio: "Jayapriya Surendran is a Software Engineer at Cloudflare currently building
      web services using Go. Prior to Cloudflare, Jayapriya worked at Athenahealth,
      One Kings Lane, and Uber. She is passionate about Large Scale Distributed Systems
      and enjoys reading, running and traveling during her free time."
      company: "Cloudflare"
      link:
        href: "https://twitter.com/jayapriya90"
        text: "@jayapriya90"
    - name: Brad Fitzpatrick
      photo: "/img/bradfitz.jpeg"
      presentation:
        time: 4:30
        title: Go 1.11 and beyond
      bio: "Brad Fitzpatrick is a software engineer at Google working
      on the Go programming language. He’s a hacker probably best known
      for LiveJournal, memcached, Perkeep (née Camlistore), and OpenID."
      company: "Google"
      link:
        href: "https://twitter.com/bradfitz"
        text: "@bradfitz"
    - presentation:
        time: 5:00
        title: Closing Remarks
